### ISSUE TITLE
test data ground truth in the dataset folder

### ISSUE THREAD

**Issue by ever4244** [microsoft/XGLUE#3]
Hi:
  I downloaded the dataset from https://xglue.blob.core.windows.net/xglue/xglue_full_dataset.tar.gz.
  For question generation task I find files like:
  xglue.qg.de.tgt.test
  xglue.qg.en.tgt.test

   Are these the ground truth of the:
   xglue.qg.de.src.test
   xglue.qg.en.src.test

   I am asking because I wonder if I can do my own evaluation by comparing my result with these files.
                                                                                                         Regards!
                                                                                                                            Wei

**Comment by Eureka6174** [comment]
Yes, you could do your won evaluation.
We just decide to release to the test data for better results reproducing.

**Comment by ever4244** [comment]
> Yes, you could do your won evaluation.
> We just decide to release to the test data for better results reproducing.

Thank you!

I asked because these ground truth files are not stated in the Data_Format.txt

I just want to make sure the result evaluated from this ground truth is comparable with the baseline results.

Thank you for the timely response.

**Comment by Eureka6174** [comment]
Thank you for your information! I will update the data format file later.
