### ISSUE TITLE
BPE dictionary in POS-tagging

### ISSUE THREAD

**Issue by ever4244** [microsoft/XGLUE#4]
Hi:
   Good evening!
   I am a little puzzled about how the BPE dictionary is used on POS-tagging in your paper (the unicoder baseline). 

for example a sentence like:
"although , as you will have seen , the dre@@ aded ' millennium bu@@ g ' failed to materi@@ alise , "
The BPE dictionary would split the word  "materialize" into   "materi@@" and  "alise"

That is fine for the translation task, however, for the POS-tagging task,  wouldn't it be better if we can keep the word `materialize' together so we can have one POS-tag for each word, instead of two POS-tag for each word-piece or two word-piece using a POS-tag together?  

So do you let the "materi@@"  "alise"  produce two "verb" label or do you let `materi@@  "alise" produces a single "verb" label (then the length of input and output would be different)

                                                                                        Regards!
                                                                                                            Wei

**Comment by Eureka6174** [comment]
Sorry for the late reply.

We only produce one verb for the first subword "materi@@". We choose this option just to follow BERT. We didn't try other options. If you have better choice, could you also tell us?

Thanks,
Yaobo
